spring.application.name=ruta-service
server.port=3337

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5437/ruta_db}
spring.datasource.username=${DB_USERNAME:ruta_user}
spring.datasource.password=${DB_PASSWORD:ruta_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.veranoperfecto.ruta=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
