spring.application.name=venta-service
server.port=3336

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5436/venta_db}
spring.datasource.username=${DB_USERNAME:venta_user}
spring.datasource.password=${DB_PASSWORD:venta_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.veranoperfecto.venta=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
